name: ci
on: [push, pull_request]
jobs:
  lint-and-run:
    name: lint and run solutions for current edition
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run lint
      - run: npm start
